server:
    # context-path: /myboot 
    session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
    port: 8082
#    uri-encoding: utf-8
#设置时间转换
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
   
        
      
  profiles: 
    active: pro
 
  devtools:
    restart:
      enabled: true    
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/*Mapper.xml

