package com.glodio.hwnbiot.beans;

public class NBCommonConst {

    public static final Long REGISTER_URL_MAX_PERIOD = 64000L;
    public static final Long REGISTER_URL_MIN_PERIOD = 1000L;
    public static final Long SECOND_TO_MILLISECOND = 1000L;
    
    // http return error code
    public static final String HTTP_ERROR_APPID_SECRET = "100208";// appId或secret错误
    public static final String HTTP_ERROR_INPUT_PARAM = "100022";// 输入参数无效
    public static final String HTTP_ERROR_REFRESH_TOKEN = "100006";// refreshToken无效
    public static final String HTTP_ERROR_TOEKN = "100002";// 错误的token信息
    public static final String HTTP_ERROR_REQUEST_AUTH = "100025";// 获取不到appId鉴权信息
    public static final String HTTP_ERROR_NULL_APPLICATION = "100203";// 应用不存在
    public static final String HTTP_ERROR_AUTH_APPLICATION = "100217";// 应用未被授权
    
    // application service and command field information
    public static final String APP_HWNBIOT_SERVICCE_ID = "SDData";
    public static final String APP_HWNBIOT_CMD_HEARTBEAT = "RESPONSE_DEVICE_BEAT";
    public static final String APP_HWNBIOT_CMD_SET_THRESHOLD = "SET_DEVICE_THRESHOLD";
    public static final String APP_HWNBIOT_CMD_SET_TIME_INTERVAL = "SET_DEVICE_TIME_INTERVAL";
    public static final String APP_HWNBIOT_CMD_ALARM_CLEAR = "SET_DEVICE_ALARM_CLEAR";
    public static final String APP_HWNBIOT_CMD_ALARM_MUTE = "SET_DEVICE_ALARM_MUTE";
    public static final String APP_HWNBIOT_CMD_REBOOT = "SET_DEVICE_REBOOT";
    public static final String APP_HWNBIOT_CMD_SENSOR_DATA = "GET_DEVICE_SENSOR_DATA";
    public static final String APP_HWNBIOT_CMD_GET_THRESHOLD = "GET_DEVICE_THRESHOLD";
    public static final String APP_HWNBIOT_CMD_GET_TIME_INTERVAL = "GET_DEVICE_TIME_INTERVAL";
    
    // common command
    public static final String APP_HWNBIOT_COMMON_SET_COMMAND = "COMMON_SET_COMMAND";
    public static final String APP_HWNBIOT_COMMON_SET_PARAMETER_COMMAND = "COMMON_SET_PARAMETER_COMMAND";
    public static final String APP_HWNBIOT_COMMON_RE_COMMAND = "COMMON_RE_COMMAND";
    
    // notify type generated by NSCL
    public static final String NOTIFY_TYPE_ACTIVE_DEVICE = "bindDevice";
    public static final String NOTIFY_TYPE_ADD_DEVICE = "deviceAdded";
    public static final String NOTIFY_TYPE_DROP_DEVICE = "deviceDeleted";
    public static final String NOTIFY_TYPE_UPDATE_DEVICEINFO = "deviceInfoChanged";
    public static final String NOTIFY_TYPE_UPDATE_DEVICEDATA = "deviceDataChanged";//设备数据上报
    public static final String NOTIFY_TYPE_UPDATE_SERVICEINFO = "serviceInfoChanged";
    public static final String NOTIFY_TYPE_MESSAGE_CONFIRM = "messageConfirm";
    public static final String NOTIFY_TYPE_COMMAND_RSP = "commandRsp";
    public static final String NOTIFY_TYPE_DEVICE_EVENT = "deviceEvent";

/*    //网关和传感器数据上报的常量
    public static final String NOTIFY_TYPE_UPDATE_DEVICE = "updateDevice";
    public static final String NOTIFY_TYPE_DELETE_SENSOR = "deleteSensor";
    public static final String NOTIFY_TYPE_ADD_SENSOR    = "addSensor";
    public static final String NOTIFY_TYPE_DELETE_DEVICE = "deleteDevice";


    //public static final String NOTIFY_TYPE_QUERY_DEVICEINFO = "queryDeviceInfo";//查询设备信息不需要callback

    // 接入设备类型, 分为网关类型设备和普通设备
    public static final String DEVICE_NODETYPE_GATEWAY = "GATEWAY";
    public static final String DEVICE_NODETYPE_ENDPOINT = "ENDPOINT";
    
    //public static boolean SUBSCRIBE_STATUS = true;//订阅状态，任意用户登录后，就设置订阅，然后设置此标志位为false
*/
}
